#!/usr/bin/env bash
# One-shot installer: register context-mode plugin into a local OpenClaw instance.
# Usage: ./scripts/install-openclaw-plugin.sh [OPENCLAW_STATE_DIR]
# Default OPENCLAW_STATE_DIR: /openclaw

set -euo pipefail

PLUGIN_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OPENCLAW_STATE_DIR="${1:-/openclaw}"
EXT_DIR="$OPENCLAW_STATE_DIR/extensions/context-mode"
RUNTIME_JSON="$OPENCLAW_STATE_DIR/runtime/openclaw.runtime.json"

echo "→ context-mode plugin installer"
echo "  plugin root : $PLUGIN_ROOT"
echo "  openclaw    : $OPENCLAW_STATE_DIR"

# 1. Build TypeScript + rebuild native bindings for system Node
echo "→ building..."
npm --prefix "$PLUGIN_ROOT" install --silent
npm --prefix "$PLUGIN_ROOT" run build
npm --prefix "$PLUGIN_ROOT" rebuild better-sqlite3

# 2. Create global extension dir (real directory — OpenClaw does NOT follow dir symlinks)
echo "→ installing extension into $EXT_DIR..."
mkdir -p "$EXT_DIR"
cp "$PLUGIN_ROOT/.openclaw-plugin/openclaw.plugin.json" "$EXT_DIR/openclaw.plugin.json"
cat > "$EXT_DIR/index.ts" << TSEOF
// context-mode OpenClaw global extension — auto-generated by install script.
// Uses absolute path so this stub can live in any extensions directory.
export { default } from "$PLUGIN_ROOT/build/openclaw-plugin.js";
TSEOF

# 3. Verify plugin is discovered by OpenClaw
echo "→ verifying discovery..."
OPENCLAW_NODE=$(node -e "require.resolve('openclaw')" 2>/dev/null | sed 's|/dist/index.js||' || true)
OPENCLAW_BIN="$(npm root -g)/openclaw/dist/index.js"
if OPENCLAW_STATE_DIR="$OPENCLAW_STATE_DIR" node "$OPENCLAW_BIN" plugins list 2>&1 | grep -q 'context-mode'; then
  echo "  ✓ context-mode discovered"
else
  echo "  ✗ plugin not discovered — check $EXT_DIR"
  exit 1
fi

# 4. Register in runtime config (idempotent)
echo "→ registering in $RUNTIME_JSON..."
python3 - "$RUNTIME_JSON" <<'PYEOF'
import json, sys
path = sys.argv[1]
with open(path) as f:
    cfg = json.load(f)
plugins = cfg.setdefault("plugins", {})
allow = plugins.setdefault("allow", [])
if "context-mode" not in allow:
    allow.insert(0, "context-mode")
entries = plugins.setdefault("entries", {})
if "context-mode" not in entries:
    entries["context-mode"] = {"enabled": True}
with open(path, "w") as f:
    json.dump(cfg, f, indent=2)
print("  plugins.allow:", allow)
PYEOF

# 5. Restart gateway
echo "→ restarting openclaw-gateway..."
if XDG_RUNTIME_DIR="/run/user/$(id -u)" systemctl --user restart openclaw-gateway 2>/dev/null; then
  echo "  ✓ gateway restarted via systemd"
else
  echo "  ⚠ restart manually: systemctl --user restart openclaw-gateway"
fi

echo ""
echo "✓ done — context-mode plugin installed and active"
